### ISSUE TITLE
Map to odom not published

### ISSUE THREAD

**Issue by PetervDooren** [tue-robotics/ed_localization#23]
We encountered a bug on the current version of master where the tf tree is incomplete, missing the link between map and odom frames. 
I am currently unsure where the cause of this lies. Could be here, hero_bringup or somewhere else. Regardless this needs to be solved asap as master is currently broken.

To replicate:
hero-start, hero-free-mode, hero-rviz.
Notice how in rviz the robot is not shown since there does not exist a transformation to the robots position.

**Comment by PetervDooren** [comment]
@MatthijsBurgh @jlunenburg you guys any idea how to debug this. I can't easily see what tf frames the localisation plugin is publishing.

**Comment by PetervDooren** [comment]
Current hypothesis: something might be wrong with the laserdata. probably the tf frame. This might still be configured with a tf prefix in gazebo.
This issue was detected in the simulator. Unknonwn if it is also an issue on the real robot. 
Edit: it is not a problem on the real robot

**Comment by MatthijsBurgh** [comment]
Extension on comment of @PetervDooren:

This only seems to be happening on 18.04/melodic. This could be explained as `gazebo_plugins` is temp build from source to fix an issue with the `tf_prefix`. There the `noetic-devel` branch is used on melodic and noetic. It might not work correctly on melodic.

**Comment by PetervDooren** [comment]
Checked the tf_frame of the laser topic. It is "base_range_sensor_link". In the localisation plugin the transformation from "base_footprint" to the this frame is needed. This part of the tf tree is intact and should not be a problem.

**Comment by MatthijsBurgh** [comment]
Resourcing of the workspace fixed the issue. As it was using the system installed version instead of the workspace version of `gazebo_plugins`.
